

#API keys for USA Today article types
usa_today_breaking_news_api_key: aey6z44bjumu4m48dfhrxb9k
usa_today_articles_api_key: c598qb7zjxd9m9d4ujqg29n7
usa_today_movies_api_key:  6935z6xmm2vpvhkub5dqk9e8
usa_today_music_api_key:  bau5qh7fk7m7jx99r39rvjw2
usa_today_snapshots_api_key:  t9sxk69qzsgh2bug3gdwudea
usa_today_sports_salaries_api_key:  3feher6aaqa3sau85hnt3bnb
